In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import warnings
warnings.filterwarnings('ignore')

cust_df = pd.read_csv('../data/train.csv', encoding = 'latin-1')
cust_df.shape

(76020, 371)

In [2]:
cust_df.head(3)

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.17,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.03,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.77,0

In [3]:
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76020 entries, 0 to 76019
Columns: 371 entries, ID to TARGET
dtypes: float64(111), int64(260)
memory usage: 215.2 MB

# 100명중 4명이 불만족하는 데이터

In [4]:
cust_df['TARGET'].value_counts() # 0: 만족, 1: 불만족
unsatisfied_cnt = cust_df[cust_df['TARGET']==1].TARGET.count()
total_cnt = cust_df.TARGET.count()

print(f'불만족 비율 : {unsatisfied_cnt/total_cnt:.2f}')

불만족 비율 : 0.04

# 최소값, Q1, Q2, Q3가 0인 피쳐가 많다
# 최소값 -999999, 000000인 피처 VAR3 > NAN > 중위값/최빈값 2로 대체

In [5]:
cust_df.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,7.602000e+04,76020.000000
mean,75964.050723,-1523.199277,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,...,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,1.172358e+05,0.039569
std,43781.947379,39033.462364,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,...,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,1.826646e+05,0.194945
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.163750e+03,0.000000
25%,38104.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.787061e+04,0.000000
50%,76043.000000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.064092e+05,0.000000
75%,113748.750000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.187563e+05,0.000000
max,151838.000000,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,...,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,2.203474e+07,1.000000

In [6]:
cust_df.var3.value_counts()

 2         74165
 8           138
-999999      116
 9           110
 3           108
           ...
 231           1
 188           1
 168           1
 135           1
 87            1
Name: var3, Length: 208, dtype: int64

## feature 선택 - id 삭제, var3은 최빈값 2로 대체체

In [16]:
cust_df.drop('ID', axis=1, inplace=True)
cust_df['var3'].replace(-999999, 2, inplace=True)
cust_df.head()

,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,imp_op_var40_ult1,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

In [17]:
# X,y 데이터 분할
X_features = cust_df.iloc[:, :-1]
y_labels = cust_df.iloc[:, -1]
X_features.shape, y_labels.shape

((76020, 369), (76020,))

In [18]:
# 훈련 / 테스트 분할
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_features, y_labels, test_size=0.2, random_state=0)
# X_train.count()
print(f'학습데이터 shape : {X_train.shape}, 테스트 데이터 shape : {X_test.shape}')

학습데이터 shape : (60816, 369), 테스트 데이터 shape : (15204, 369)

In [19]:
train_cnt = y_train.count()
test_cnt = y_test.count()
print(f'학습 데이터 값의 비율 : {y_train.value_counts()/train_cnt}, 테스트 세트 레이블 값 분포 비율 : {y_test.value_counts()/test_cnt}')

학습 데이터 값의 비율 : 0    0.960964
1    0.039036
Name: TARGET, dtype: float64, 테스트 세트 레이블 값 분포 비율 : 0    0.9583
1    0.0417
Name: TARGET, dtype: float64

In [20]:
# DT 예측기

In [21]:
# RF 예측기

# XGBoost 예측기

## 훈련데이터 > 훈련 * 검증 분할

In [22]:
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=0)

## XGBosst model

In [23]:
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score

xgb_clf = XGBClassifier(n_estimator = 500, learing_rate = 0.05, random_state = 156)
xgb_clf.fit(X_tr,y_tr, early_stopping_rounds = 100, eval_metric='auc', eval_set =[(X_tr, y_tr), (X_val, y_val)])
xgb_roc_score = roc_auc_score(y_test, xgb_clf.predict_proba(X_test)[:, 1])
xgb_roc_score

[14:26:07] WARNING: D:\bld\xgboost-split_1637426510059\work\src\learner.cc:576:
Parameters: { "learing_rate", "n_estimator" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[0]	validation_0-auc:0.82179	validation_1-auc:0.80068
[1]	validation_0-auc:0.83374	validation_1-auc:0.80818
[2]	validation_0-auc:0.83855	validation_1-auc:0.81008
[3]	validation_0-auc:0.84400	validation_1-auc:0.81515
[4]	validation_0-auc:0.84723	validation_1-auc:0.81543
[5]	validation_0-auc:0.85252	validation_1-auc:0.81729
[6]	validation_0-auc:0.85937	validation_1-auc:0.82418
[7]	validation_0-auc:0.86427	validation_1-auc:0.82763
[8]	validation_0-auc:0.86932	validation_1-auc:0.82938
[9]	validation_0-auc:0.87190	validation_1-auc:0.83084
[10]	validation_0-auc:0.87693	validation_1-auc:0.83024
[11]	validation_0-auc:0.87993	validation_1-auc:0.83020
[12]	validation_0-auc:0.88287	validation_1-auc:0.83066
[13]	validation_0-auc:0.88666	validation_1-auc:0.83068
[14]	validation_0-auc:0.88909	validation_1-auc:0.83108
[15]	validation_0-auc:0.89169	validation_1-auc:0.83058
[16]	validation_0-auc:0.89311	validation_1-auc:0.83039
[17]	validation_0-auc:0.89420	validation_1-auc:0.83008
[18]	validation_0-auc:0.89596	validation_1-auc:0.82986
[19]	validation_0-auc:0.89719	validation_1-auc:0.83041
[20]	validation_0-auc:0.89934	validation_1-auc:0.83088
[21]	validation_0-auc:0.90026	validation_1-auc:0.83128
[22]	validation_0-auc:0.90059	validation_1-auc:0.83166
[23]	validation_0-auc:0.90091	validation_1-auc:0.83170
[24]	validation_0-auc:0.90246	validation_1-auc:0.83166
[25]	validation_0-auc:0.90305	validation_1-auc:0.83116
[26]	validation_0-auc:0.90400	validation_1-auc:0.83124
[27]	validation_0-auc:0.90477	validation_1-auc:0.83087
[28]	validation_0-auc:0.90500	validation_1-auc:0.83051
[29]	validation_0-auc:0.90628	validation_1-auc:0.83044
[30]	validation_0-auc:0.90709	validation_1-auc:0.83038
[31]	validation_0-auc:0.90802	validation_1-auc:0.83017
[32]	validation_0-auc:0.90835	validation_1-auc:0.83020
[33]	validation_0-auc:0.90933	validation_1-auc:0.83023
[34]	validation_0-auc:0.91093	validation_1-auc:0.82947
[35]	validation_0-auc:0.91141	validation_1-auc:0.82927
[36]	validation_0-auc:0.91151	validation_1-auc:0.82906
[37]	validation_0-auc:0.91280	validation_1-auc:0.82877
[38]	validation_0-auc:0.91339	validation_1-auc:0.82860
[39]	validation_0-auc:0.91435	validation_1-auc:0.82864
[40]	validation_0-auc:0.91438	validation_1-auc:0.82898
[41]	validation_0-auc:0.91543	validation_1-auc:0.82875
[42]	validation_0-auc:0.91568	validation_1-auc:0.82862
[43]	validation_0-auc:0.91592	validation_1-auc:0.82838
[44]	validation_0-auc:0.91683	validation_1-auc:0.82806
[45]	validation_0-auc:0.91701	validation_1-auc:0.82800
[46]	validation_0-auc:0.91711	validation_1-auc:0.82807
[47]	validation_0-auc:0.91741	validation_1-auc:0.82784
[48]	validation_0-auc:0.91764	validation_1-auc:0.82789
[49]	validation_0-auc:0.91773	validation_1-auc:0.82773
[50]	validation_0-auc:0.91777	validation_1-auc:0.82765
[51]	validation_0-auc:0.91899	validation_1-auc:0.82731
[52]	validation_0-auc:0.91944	validation_1-auc:0.82708
[53]	validation_0-auc:0.92033	validation_1-auc:0.82679
[54]	validation_0-auc:0.92185	validation_1-auc:0.82632
[55]	validation_0-auc:0.92200	validation_1-auc:0.82628
[56]	validation_0-auc:0.92229	validation_1-auc:0.82597
[57]	validation_0-auc:0.92245	validation_1-auc:0.82574
[58]	validation_0-auc:0.92314	validation_1-auc:0.82542
[59]	validation_0-auc:0.92335	validation_1-auc:0.82533
[60]	validation_0-auc:0.92372	validation_1-auc:0.82515
[61]	validation_0-auc:0.92431	validation_1-auc:0.82498
[62]	validation_0-auc:0.92583	validation_1-auc:0.82437
[63]	validation_0-auc:0.92758	validation_1-auc:0.82445
[64]	validation_0-auc:0.92883	validation_1-auc:0.82494
[65]	validation_0-auc:0.92929	validation_1-auc:0.82464
[66]	validation_0-auc:0.93032	validation_1-auc:0.82449
[67]	validation_0-auc:0.93062	validation_1-auc:0.82409
[68]	validation_0-auc:0.93091	validation_1-auc:0.82393
[69]	validation_0-auc:0.93118	validation_1-auc:0.82375
[70]	validation_0-auc:0.93125	validation_1-auc:0.82367
[71]	validation_0-auc:0.93137	validation_1-auc:0.82371
[72]	validation_0-auc:0.93151	validation_1-auc:0.82345
[73]	validation_0-auc:0.93158	validation_1-auc:0.82346
[74]	validation_0-auc:0.93276	validation_1-auc:0.82342
[75]	validation_0-auc:0.93289	validation_1-auc:0.82326
[76]	validation_0-auc:0.93324	validation_1-auc:0.82336
[77]	validation_0-auc:0.93365	validation_1-auc:0.82328
[78]	validation_0-auc:0.93379	validation_1-auc:0.82352
[79]	validation_0-auc:0.93442	validation_1-auc:0.82328
[80]	validation_0-auc:0.93476	validation_1-auc:0.82313
[81]	validation_0-auc:0.93583	validation_1-auc:0.82282
[82]	validation_0-auc:0.93761	validation_1-auc:0.82264
[83]	validation_0-auc:0.93865	validation_1-auc:0.82195
[84]	validation_0-auc:0.93896	validation_1-auc:0.82173
[85]	validation_0-auc:0.94028	validation_1-auc:0.82176
[86]	validation_0-auc:0.94111	validation_1-auc:0.82086
[87]	validation_0-auc:0.94145	validation_1-auc:0.82100
[88]	validation_0-auc:0.94322	validation_1-auc:0.82106
[89]	validation_0-auc:0.94338	validation_1-auc:0.82138
[90]	validation_0-auc:0.94351	validation_1-auc:0.82095
[91]	validation_0-auc:0.94465	validation_1-auc:0.82073
[92]	validation_0-auc:0.94465	validation_1-auc:0.82079
[93]	validation_0-auc:0.94554	validation_1-auc:0.82044
[94]	validation_0-auc:0.94558	validation_1-auc:0.82065
[95]	validation_0-auc:0.94577	validation_1-auc:0.82086
[96]	validation_0-auc:0.94603	validation_1-auc:0.82103
[97]	validation_0-auc:0.94610	validation_1-auc:0.82102
[98]	validation_0-auc:0.94678	validation_1-auc:0.82038
[99]	validation_0-auc:0.94683	validation_1-auc:0.82027

0.8415464125109068

# 최적화 파라미터
n_estimator = 500
learning_rate = 0.15
max_depth = 5

# 하이퍼 오피티 파라미터  최적화화

In [26]:
from hyperopt.pyll.base import scope
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from hyperopt import fmin, tpe, Trials, hp

# 하이퍼파라미터 검색공간
search_space = { 'n_estimator': scope.int(hp.quniform('n_estimator', 50, 300, 10)), 
                'max_depth': scope.int(hp.quniform('max_depth', 3, 10, 1)),
                'learning_rate': hp.loguniform('learning_rate', np.log(0.01), np.log(0.3)),
                'subsample':hp.uniform('subsample', 0.5, 1.0),
                'colsample_bytree': hp.uniform('colsample_bytree', 0.5, 1.0),
                }

In [31]:
from hyperopt import fmin, tpe, Trials, STATUS_OK
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score

def objective_func_xgb(params):
    model = XGBClassifier(
        n_estimators=100, # params['n_estimator'],
        max_depth = params['max_depth'],
        learning_rate = params['learning_rate'],
        # subsample=params['subsample'],
        colsample_bytree=params['colsample_bytree'],
        random_state=42,
        eval_metric='logloss'
    )
    score_mean = cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy').mean()
    return {'loss': -score_mean, 'status': STATUS_OK}

In [32]:
trials = Trials()

best_params = fmin(
    fn=objective_func_xgb,
    space=search_space,
    algo= tpe.suggest,
    max_evals=50,
    trials= trials 
    )

100%|██████████| 50/50 [16:18<00:00, 19.57s/trial, best loss: -0.9610299907133951]

In [36]:
best_params

{'colsample_bytree': 0.5160548964359934,
 'learning_rate': 0.017265107835005757,
 'max_depth': 7.0,
 'n_estimator': 230.0,
 'subsample': 0.8827289415806837}

In [41]:
best_model = XGBClassifier(n_estimators = int(best_params['n_estimator']),
                           learning_rate = best_params['learning_rate'],
                           max_depth = int(best_params['max_depth']),
                           subsample=best_params['subsample'],
                           colsample_bytree = best_params['colsample_bytree'],
                           random_state = 42,
                           eval_metric= 'logloss'
                           )

In [42]:
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=0)

In [43]:
eval_list = [(X_tr, y_tr), (X_val,y_val)]

best_model.fit(X_tr,y_tr,
                early_stopping_rounds = 100,
                eval_set = eval_list,
                eval_metric = 'auc'
                )

[0]	validation_0-auc:0.72291	validation_1-auc:0.70037
[1]	validation_0-auc:0.76606	validation_1-auc:0.73839
[2]	validation_0-auc:0.77145	validation_1-auc:0.73998
[3]	validation_0-auc:0.77114	validation_1-auc:0.73802
[4]	validation_0-auc:0.77221	validation_1-auc:0.73755
[5]	validation_0-auc:0.77396	validation_1-auc:0.73997
[6]	validation_0-auc:0.81084	validation_1-auc:0.78308
[7]	validation_0-auc:0.81020	validation_1-auc:0.78238
[8]	validation_0-auc:0.81037	validation_1-auc:0.78256
[9]	validation_0-auc:0.81937	validation_1-auc:0.79259
[10]	validation_0-auc:0.81927	validation_1-auc:0.79142
[11]	validation_0-auc:0.82596	validation_1-auc:0.79826
[12]	validation_0-auc:0.82449	validation_1-auc:0.79609
[13]	validation_0-auc:0.82863	validation_1-auc:0.80141
[14]	validation_0-auc:0.82759	validation_1-auc:0.80026
[15]	validation_0-auc:0.82743	validation_1-auc:0.79986
[16]	validation_0-auc:0.82949	validation_1-auc:0.80206
[17]	validation_0-auc:0.82925	validation_1-auc:0.80143
[18]	validation_0-auc:0.82960	validation_1-auc:0.80100
[19]	validation_0-auc:0.82919	validation_1-auc:0.80095
[20]	validation_0-auc:0.82886	validation_1-auc:0.80006
[21]	validation_0-auc:0.83100	validation_1-auc:0.80149
[22]	validation_0-auc:0.83072	validation_1-auc:0.80056
[23]	validation_0-auc:0.83238	validation_1-auc:0.80173
[24]	validation_0-auc:0.83378	validation_1-auc:0.80352
[25]	validation_0-auc:0.83327	validation_1-auc:0.80296
[26]	validation_0-auc:0.83537	validation_1-auc:0.80433
[27]	validation_0-auc:0.83499	validation_1-auc:0.80405
[28]	validation_0-auc:0.83435	validation_1-auc:0.80314
[29]	validation_0-auc:0.83579	validation_1-auc:0.80502
[30]	validation_0-auc:0.83747	validation_1-auc:0.80664
[31]	validation_0-auc:0.83897	validation_1-auc:0.80776
[32]	validation_0-auc:0.83851	validation_1-auc:0.80717
[33]	validation_0-auc:0.83995	validation_1-auc:0.80882
[34]	validation_0-auc:0.84101	validation_1-auc:0.80961
[35]	validation_0-auc:0.84083	validation_1-auc:0.80950
[36]	validation_0-auc:0.84176	validation_1-auc:0.81039
[37]	validation_0-auc:0.84278	validation_1-auc:0.81131
[38]	validation_0-auc:0.84282	validation_1-auc:0.81124
[39]	validation_0-auc:0.84382	validation_1-auc:0.81169
[40]	validation_0-auc:0.84318	validation_1-auc:0.81119
[41]	validation_0-auc:0.84383	validation_1-auc:0.81195
[42]	validation_0-auc:0.84461	validation_1-auc:0.81249
[43]	validation_0-auc:0.84569	validation_1-auc:0.81334
[44]	validation_0-auc:0.84585	validation_1-auc:0.81291
[45]	validation_0-auc:0.84664	validation_1-auc:0.81361
[46]	validation_0-auc:0.84751	validation_1-auc:0.81446
[47]	validation_0-auc:0.84732	validation_1-auc:0.81406
[48]	validation_0-auc:0.84823	validation_1-auc:0.81493
[49]	validation_0-auc:0.84882	validation_1-auc:0.81459
[50]	validation_0-auc:0.84874	validation_1-auc:0.81463
[51]	validation_0-auc:0.84834	validation_1-auc:0.81407
[52]	validation_0-auc:0.84823	validation_1-auc:0.81409
[53]	validation_0-auc:0.84951	validation_1-auc:0.81483
[54]	validation_0-auc:0.85059	validation_1-auc:0.81493
[55]	validation_0-auc:0.85067	validation_1-auc:0.81463
[56]	validation_0-auc:0.85140	validation_1-auc:0.81492
[57]	validation_0-auc:0.85206	validation_1-auc:0.81533
[58]	validation_0-auc:0.85286	validation_1-auc:0.81616
[59]	validation_0-auc:0.85251	validation_1-auc:0.81617
[60]	validation_0-auc:0.85207	validation_1-auc:0.81573
[61]	validation_0-auc:0.85215	validation_1-auc:0.81526
[62]	validation_0-auc:0.85269	validation_1-auc:0.81589
[63]	validation_0-auc:0.85297	validation_1-auc:0.81545
[64]	validation_0-auc:0.85379	validation_1-auc:0.81617
[65]	validation_0-auc:0.85440	validation_1-auc:0.81668
[66]	validation_0-auc:0.85562	validation_1-auc:0.81821
[67]	validation_0-auc:0.85630	validation_1-auc:0.81897
[68]	validation_0-auc:0.85700	validation_1-auc:0.81930
[69]	validation_0-auc:0.85720	validation_1-auc:0.81898
[70]	validation_0-auc:0.85699	validation_1-auc:0.81851
[71]	validation_0-auc:0.85794	validation_1-auc:0.81926
[72]	validation_0-auc:0.85777	validation_1-auc:0.81885
[73]	validation_0-auc:0.85781	validation_1-auc:0.81865
[74]	validation_0-auc:0.85775	validation_1-auc:0.81822
[75]	validation_0-auc:0.85750	validation_1-auc:0.81744
[76]	validation_0-auc:0.85717	validation_1-auc:0.81698
[77]	validation_0-auc:0.85704	validation_1-auc:0.81678
[78]	validation_0-auc:0.85815	validation_1-auc:0.81751
[79]	validation_0-auc:0.85822	validation_1-auc:0.81704
[80]	validation_0-auc:0.85791	validation_1-auc:0.81687
[81]	validation_0-auc:0.85775	validation_1-auc:0.81645
[82]	validation_0-auc:0.85822	validation_1-auc:0.81685
[83]	validation_0-auc:0.85876	validation_1-auc:0.81723
[84]	validation_0-auc:0.85923	validation_1-auc:0.81771
[85]	validation_0-auc:0.85994	validation_1-auc:0.81832
[86]	validation_0-auc:0.86102	validation_1-auc:0.81972
[87]	validation_0-auc:0.86187	validation_1-auc:0.82048
[88]	validation_0-auc:0.86199	validation_1-auc:0.82001
[89]	validation_0-auc:0.86249	validation_1-auc:0.82069
[90]	validation_0-auc:0.86318	validation_1-auc:0.82126
[91]	validation_0-auc:0.86311	validation_1-auc:0.82088
[92]	validation_0-auc:0.86344	validation_1-auc:0.82142
[93]	validation_0-auc:0.86359	validation_1-auc:0.82164
[94]	validation_0-auc:0.86357	validation_1-auc:0.82113
[95]	validation_0-auc:0.86406	validation_1-auc:0.82144
[96]	validation_0-auc:0.86400	validation_1-auc:0.82124
[97]	validation_0-auc:0.86439	validation_1-auc:0.82195
[98]	validation_0-auc:0.86452	validation_1-auc:0.82175
[99]	validation_0-auc:0.86514	validation_1-auc:0.82205
[100]	validation_0-auc:0.86537	validation_1-auc:0.82203
[101]	validation_0-auc:0.86593	validation_1-auc:0.82211
[102]	validation_0-auc:0.86658	validation_1-auc:0.82233
[103]	validation_0-auc:0.86719	validation_1-auc:0.82251
[104]	validation_0-auc:0.86781	validation_1-auc:0.82273
[105]	validation_0-auc:0.86820	validation_1-auc:0.82285
[106]	validation_0-auc:0.86877	validation_1-auc:0.82314
[107]	validation_0-auc:0.86905	validation_1-auc:0.82333
[108]	validation_0-auc:0.86907	validation_1-auc:0.82341
[109]	validation_0-auc:0.86922	validation_1-auc:0.82328
[110]	validation_0-auc:0.86923	validation_1-auc:0.82309
[111]	validation_0-auc:0.86986	validation_1-auc:0.82333
[112]	validation_0-auc:0.86970	validation_1-auc:0.82335
[113]	validation_0-auc:0.86966	validation_1-auc:0.82319
[114]	validation_0-auc:0.86980	validation_1-auc:0.82297
[115]	validation_0-auc:0.87023	validation_1-auc:0.82351
[116]	validation_0-auc:0.87092	validation_1-auc:0.82371
[117]	validation_0-auc:0.87146	validation_1-auc:0.82392
[118]	validation_0-auc:0.87180	validation_1-auc:0.82412
[119]	validation_0-auc:0.87223	validation_1-auc:0.82440
[120]	validation_0-auc:0.87260	validation_1-auc:0.82462
[121]	validation_0-auc:0.87263	validation_1-auc:0.82464
[122]	validation_0-auc:0.87262	validation_1-auc:0.82479
[123]	validation_0-auc:0.87313	validation_1-auc:0.82491
[124]	validation_0-auc:0.87363	validation_1-auc:0.82512
[125]	validation_0-auc:0.87387	validation_1-auc:0.82513
[126]	validation_0-auc:0.87391	validation_1-auc:0.82490
[127]	validation_0-auc:0.87428	validation_1-auc:0.82522
[128]	validation_0-auc:0.87456	validation_1-auc:0.82553
[129]	validation_0-auc:0.87463	validation_1-auc:0.82566
[130]	validation_0-auc:0.87465	validation_1-auc:0.82555
[131]	validation_0-auc:0.87465	validation_1-auc:0.82547
[132]	validation_0-auc:0.87480	validation_1-auc:0.82544
[133]	validation_0-auc:0.87514	validation_1-auc:0.82574
[134]	validation_0-auc:0.87555	validation_1-auc:0.82587
[135]	validation_0-auc:0.87572	validation_1-auc:0.82552
[136]	validation_0-auc:0.87594	validation_1-auc:0.82547
[137]	validation_0-auc:0.87599	validation_1-auc:0.82563
[138]	validation_0-auc:0.87596	validation_1-auc:0.82558
[139]	validation_0-auc:0.87600	validation_1-auc:0.82552
[140]	validation_0-auc:0.87590	validation_1-auc:0.82536
[141]	validation_0-auc:0.87572	validation_1-auc:0.82521
[142]	validation_0-auc:0.87634	validation_1-auc:0.82556
[143]	validation_0-auc:0.87690	validation_1-auc:0.82582
[144]	validation_0-auc:0.87738	validation_1-auc:0.82617
[145]	validation_0-auc:0.87765	validation_1-auc:0.82642
[146]	validation_0-auc:0.87820	validation_1-auc:0.82658
[147]	validation_0-auc:0.87847	validation_1-auc:0.82685
[148]	validation_0-auc:0.87856	validation_1-auc:0.82671
[149]	validation_0-auc:0.87901	validation_1-auc:0.82701
[150]	validation_0-auc:0.87927	validation_1-auc:0.82727
[151]	validation_0-auc:0.87969	validation_1-auc:0.82730
[152]	validation_0-auc:0.88007	validation_1-auc:0.82763
[153]	validation_0-auc:0.88034	validation_1-auc:0.82783
[154]	validation_0-auc:0.88039	validation_1-auc:0.82771
[155]	validation_0-auc:0.88082	validation_1-auc:0.82782
[156]	validation_0-auc:0.88104	validation_1-auc:0.82765
[157]	validation_0-auc:0.88114	validation_1-auc:0.82756
[158]	validation_0-auc:0.88106	validation_1-auc:0.82756
[159]	validation_0-auc:0.88104	validation_1-auc:0.82743
[160]	validation_0-auc:0.88115	validation_1-auc:0.82730
[161]	validation_0-auc:0.88152	validation_1-auc:0.82741
[162]	validation_0-auc:0.88194	validation_1-auc:0.82767
[163]	validation_0-auc:0.88229	validation_1-auc:0.82795
[164]	validation_0-auc:0.88236	validation_1-auc:0.82787
[165]	validation_0-auc:0.88228	validation_1-auc:0.82775
[166]	validation_0-auc:0.88233	validation_1-auc:0.82760
[167]	validation_0-auc:0.88246	validation_1-auc:0.82744
[168]	validation_0-auc:0.88286	validation_1-auc:0.82765
[169]	validation_0-auc:0.88288	validation_1-auc:0.82754
[170]	validation_0-auc:0.88291	validation_1-auc:0.82738
[171]	validation_0-auc:0.88286	validation_1-auc:0.82737
[172]	validation_0-auc:0.88337	validation_1-auc:0.82761
[173]	validation_0-auc:0.88334	validation_1-auc:0.82736
[174]	validation_0-auc:0.88360	validation_1-auc:0.82755
[175]	validation_0-auc:0.88382	validation_1-auc:0.82753
[176]	validation_0-auc:0.88375	validation_1-auc:0.82755
[177]	validation_0-auc:0.88382	validation_1-auc:0.82756
[178]	validation_0-auc:0.88433	validation_1-auc:0.82787
[179]	validation_0-auc:0.88479	validation_1-auc:0.82821
[180]	validation_0-auc:0.88480	validation_1-auc:0.82820
[181]	validation_0-auc:0.88531	validation_1-auc:0.82828
[182]	validation_0-auc:0.88532	validation_1-auc:0.82823
[183]	validation_0-auc:0.88581	validation_1-auc:0.82834
[184]	validation_0-auc:0.88601	validation_1-auc:0.82843
[185]	validation_0-auc:0.88636	validation_1-auc:0.82870
[186]	validation_0-auc:0.88641	validation_1-auc:0.82867
[187]	validation_0-auc:0.88637	validation_1-auc:0.82864
[188]	validation_0-auc:0.88674	validation_1-auc:0.82881
[189]	validation_0-auc:0.88685	validation_1-auc:0.82878
[190]	validation_0-auc:0.88734	validation_1-auc:0.82900
[191]	validation_0-auc:0.88769	validation_1-auc:0.82909
[192]	validation_0-auc:0.88830	validation_1-auc:0.82917
[193]	validation_0-auc:0.88853	validation_1-auc:0.82913
[194]	validation_0-auc:0.88902	validation_1-auc:0.82934
[195]	validation_0-auc:0.88918	validation_1-auc:0.82931
[196]	validation_0-auc:0.88943	validation_1-auc:0.82945
[197]	validation_0-auc:0.88973	validation_1-auc:0.82961
[198]	validation_0-auc:0.89017	validation_1-auc:0.82973
[199]	validation_0-auc:0.89016	validation_1-auc:0.82968
[200]	validation_0-auc:0.89062	validation_1-auc:0.82983
[201]	validation_0-auc:0.89064	validation_1-auc:0.82969
[202]	validation_0-auc:0.89066	validation_1-auc:0.82964
[203]	validation_0-auc:0.89109	validation_1-auc:0.82988
[204]	validation_0-auc:0.89140	validation_1-auc:0.83001
[205]	validation_0-auc:0.89146	validation_1-auc:0.82991
[206]	validation_0-auc:0.89164	validation_1-auc:0.82997
[207]	validation_0-auc:0.89196	validation_1-auc:0.82995
[208]	validation_0-auc:0.89212	validation_1-auc:0.82980
[209]	validation_0-auc:0.89251	validation_1-auc:0.83001
[210]	validation_0-auc:0.89289	validation_1-auc:0.83020
[211]	validation_0-auc:0.89344	validation_1-auc:0.83044
[212]	validation_0-auc:0.89357	validation_1-auc:0.83027
[213]	validation_0-auc:0.89371	validation_1-auc:0.83021
[214]	validation_0-auc:0.89390	validation_1-auc:0.83018
[215]	validation_0-auc:0.89428	validation_1-auc:0.83041
[216]	validation_0-auc:0.89437	validation_1-auc:0.83035
[217]	validation_0-auc:0.89466	validation_1-auc:0.83050
[218]	validation_0-auc:0.89515	validation_1-auc:0.83066
[219]	validation_0-auc:0.89516	validation_1-auc:0.83065
[220]	validation_0-auc:0.89548	validation_1-auc:0.83092
[221]	validation_0-auc:0.89579	validation_1-auc:0.83114
[222]	validation_0-auc:0.89591	validation_1-auc:0.83100
[223]	validation_0-auc:0.89619	validation_1-auc:0.83110
[224]	validation_0-auc:0.89652	validation_1-auc:0.83123
[225]	validation_0-auc:0.89671	validation_1-auc:0.83140
[226]	validation_0-auc:0.89707	validation_1-auc:0.83162
[227]	validation_0-auc:0.89711	validation_1-auc:0.83140
[228]	validation_0-auc:0.89728	validation_1-auc:0.83137
[229]	validation_0-auc:0.89764	validation_1-auc:0.83164

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.5160548964359934,
              enable_categorical=False, eval_metric='logloss', gamma=0,
              gpu_id=-1, importance_type=None, interaction_constraints='',
              learning_rate=0.017265107835005757, max_delta_step=0, max_depth=7,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=230, n_jobs=20, num_parallel_tree=1,
              predictor='auto', random_state=42, reg_alpha=0, reg_lambda=1,
              scale_pos_weight=1, subsample=0.8827289415806837,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [44]:
from sklearn.metrics import roc_auc_score
xgb_roc_score = roc_auc_score(y_test, best_model.predict_proba(X_test)[:,1])
xgb_roc_score

0.8442884237738406

# LGBM으로 돌리기기

In [ ]:
from lightgbm import LGBMClassifier
from sklearn.metrics import roc_auc_score

lgbm_clf = LGBMClassifier(n_estimators=500, learning_rate=0.05, random_state=156)

eval_list = [(X_tr, y_tr), (X_val, y_val)]  # 훈련용, 검증용 데이터 평가목록
lgbm_clf.fit(X_tr, y_tr, 
             early_stopping_rounds=100, 
             eval_metric='logloss', 
             eval_set=eval_list, 
             verbose=True)

[1]	training's binary_logloss: 0.159747	valid_1's binary_logloss: 0.161487
[2]	training's binary_logloss: 0.155995	valid_1's binary_logloss: 0.158489
[3]	training's binary_logloss: 0.152875	valid_1's binary_logloss: 0.155925
[4]	training's binary_logloss: 0.150255	valid_1's binary_logloss: 0.153849
[5]	training's binary_logloss: 0.148052	valid_1's binary_logloss: 0.152054
[6]	training's binary_logloss: 0.146074	valid_1's binary_logloss: 0.1505
[7]	training's binary_logloss: 0.144325	valid_1's binary_logloss: 0.149162
[8]	training's binary_logloss: 0.142724	valid_1's binary_logloss: 0.14795
[9]	training's binary_logloss: 0.141297	valid_1's binary_logloss: 0.146862
[10]	training's binary_logloss: 0.139983	valid_1's binary_logloss: 0.145886
[11]	training's binary_logloss: 0.138763	valid_1's binary_logloss: 0.144993
[12]	training's binary_logloss: 0.137652	valid_1's binary_logloss: 0.14414
[13]	training's binary_logloss: 0.136616	valid_1's binary_logloss: 0.1434
[14]	training's binary_logloss: 0.135651	valid_1's binary_logloss: 0.142704
[15]	training's binary_logloss: 0.134786	valid_1's binary_logloss: 0.142119
[16]	training's binary_logloss: 0.13392	valid_1's binary_logloss: 0.141507
[17]	training's binary_logloss: 0.133095	valid_1's binary_logloss: 0.141041
[18]	training's binary_logloss: 0.132328	valid_1's binary_logloss: 0.140619
[19]	training's binary_logloss: 0.131665	valid_1's binary_logloss: 0.140197
[20]	training's binary_logloss: 0.131013	valid_1's binary_logloss: 0.139761
[21]	training's binary_logloss: 0.130344	valid_1's binary_logloss: 0.139332
[22]	training's binary_logloss: 0.129721	valid_1's binary_logloss: 0.138971
[23]	training's binary_logloss: 0.129159	valid_1's binary_logloss: 0.138647
[24]	training's binary_logloss: 0.128625	valid_1's binary_logloss: 0.138353
[25]	training's binary_logloss: 0.128103	valid_1's binary_logloss: 0.138153
[26]	training's binary_logloss: 0.127585	valid_1's binary_logloss: 0.137908
[27]	training's binary_logloss: 0.127107	valid_1's binary_logloss: 0.137726
[28]	training's binary_logloss: 0.126637	valid_1's binary_logloss: 0.137533
[29]	training's binary_logloss: 0.126183	valid_1's binary_logloss: 0.137354
[30]	training's binary_logloss: 0.125738	valid_1's binary_logloss: 0.137151
[31]	training's binary_logloss: 0.125293	valid_1's binary_logloss: 0.137
[32]	training's binary_logloss: 0.124867	valid_1's binary_logloss: 0.136828
[33]	training's binary_logloss: 0.124516	valid_1's binary_logloss: 0.136686
[34]	training's binary_logloss: 0.124158	valid_1's binary_logloss: 0.136544
[35]	training's binary_logloss: 0.12377	valid_1's binary_logloss: 0.136452
[36]	training's binary_logloss: 0.123426	valid_1's binary_logloss: 0.136348
[37]	training's binary_logloss: 0.123069	valid_1's binary_logloss: 0.136197
[38]	training's binary_logloss: 0.122696	valid_1's binary_logloss: 0.136108
[39]	training's binary_logloss: 0.122369	valid_1's binary_logloss: 0.13602
[40]	training's binary_logloss: 0.122066	valid_1's binary_logloss: 0.135936
[41]	training's binary_logloss: 0.121787	valid_1's binary_logloss: 0.135801
[42]	training's binary_logloss: 0.121475	valid_1's binary_logloss: 0.135725
[43]	training's binary_logloss: 0.121153	valid_1's binary_logloss: 0.135692
[44]	training's binary_logloss: 0.120861	valid_1's binary_logloss: 0.135575
[45]	training's binary_logloss: 0.12054	valid_1's binary_logloss: 0.135485
[46]	training's binary_logloss: 0.120258	valid_1's binary_logloss: 0.135446
[47]	training's binary_logloss: 0.119952	valid_1's binary_logloss: 0.135414
[48]	training's binary_logloss: 0.119684	valid_1's binary_logloss: 0.135391
[49]	training's binary_logloss: 0.119366	valid_1's binary_logloss: 0.135345
[50]	training's binary_logloss: 0.119136	valid_1's binary_logloss: 0.135296
[51]	training's binary_logloss: 0.118869	valid_1's binary_logloss: 0.13527
[52]	training's binary_logloss: 0.118628	valid_1's binary_logloss: 0.135213
[53]	training's binary_logloss: 0.118382	valid_1's binary_logloss: 0.135207
[54]	training's binary_logloss: 0.118134	valid_1's binary_logloss: 0.135149
[55]	training's binary_logloss: 0.117892	valid_1's binary_logloss: 0.135125
[56]	training's binary_logloss: 0.117657	valid_1's binary_logloss: 0.135067
[57]	training's binary_logloss: 0.117456	valid_1's binary_logloss: 0.13503
[58]	training's binary_logloss: 0.11721	valid_1's binary_logloss: 0.135023
[59]	training's binary_logloss: 0.11701	valid_1's binary_logloss: 0.134999
[60]	training's binary_logloss: 0.116778	valid_1's binary_logloss: 0.135007
[61]	training's binary_logloss: 0.116547	valid_1's binary_logloss: 0.134961
[62]	training's binary_logloss: 0.116334	valid_1's binary_logloss: 0.134924
[63]	training's binary_logloss: 0.116105	valid_1's binary_logloss: 0.134944
[64]	training's binary_logloss: 0.115904	valid_1's binary_logloss: 0.134897
[65]	training's binary_logloss: 0.115747	valid_1's binary_logloss: 0.134873
[66]	training's binary_logloss: 0.115552	valid_1's binary_logloss: 0.134877
[67]	training's binary_logloss: 0.115384	valid_1's binary_logloss: 0.13486
[68]	training's binary_logloss: 0.115165	valid_1's binary_logloss: 0.134824
[69]	training's binary_logloss: 0.114964	valid_1's binary_logloss: 0.134841
[70]	training's binary_logloss: 0.114778	valid_1's binary_logloss: 0.134871
[71]	training's binary_logloss: 0.114608	valid_1's binary_logloss: 0.134863
[72]	training's binary_logloss: 0.114414	valid_1's binary_logloss: 0.134845
[73]	training's binary_logloss: 0.114198	valid_1's binary_logloss: 0.134859
[74]	training's binary_logloss: 0.11402	valid_1's binary_logloss: 0.134851
[75]	training's binary_logloss: 0.113794	valid_1's binary_logloss: 0.134863
[76]	training's binary_logloss: 0.113652	valid_1's binary_logloss: 0.134829
[77]	training's binary_logloss: 0.113483	valid_1's binary_logloss: 0.134821
[78]	training's binary_logloss: 0.113292	valid_1's binary_logloss: 0.134828
[79]	training's binary_logloss: 0.113142	valid_1's binary_logloss: 0.134828
[80]	training's binary_logloss: 0.112989	valid_1's binary_logloss: 0.134777
[81]	training's binary_logloss: 0.112805	valid_1's binary_logloss: 0.13481
[82]	training's binary_logloss: 0.112665	valid_1's binary_logloss: 0.134787
[83]	training's binary_logloss: 0.112518	valid_1's binary_logloss: 0.134776
[84]	training's binary_logloss: 0.112369	valid_1's binary_logloss: 0.134742
[85]	training's binary_logloss: 0.11222	valid_1's binary_logloss: 0.134719
[86]	training's binary_logloss: 0.112089	valid_1's binary_logloss: 0.134711
[87]	training's binary_logloss: 0.111956	valid_1's binary_logloss: 0.134734
[88]	training's binary_logloss: 0.111785	valid_1's binary_logloss: 0.134752
[89]	training's binary_logloss: 0.111659	valid_1's binary_logloss: 0.134743
[90]	training's binary_logloss: 0.111473	valid_1's binary_logloss: 0.134725
[91]	training's binary_logloss: 0.111304	valid_1's binary_logloss: 0.134722
[92]	training's binary_logloss: 0.111154	valid_1's binary_logloss: 0.13476
[93]	training's binary_logloss: 0.11103	valid_1's binary_logloss: 0.134738
[94]	training's binary_logloss: 0.110871	valid_1's binary_logloss: 0.134735
[95]	training's binary_logloss: 0.110753	valid_1's binary_logloss: 0.134728
[96]	training's binary_logloss: 0.110633	valid_1's binary_logloss: 0.134709
[97]	training's binary_logloss: 0.110494	valid_1's binary_logloss: 0.134677
[98]	training's binary_logloss: 0.110349	valid_1's binary_logloss: 0.134701
[99]	training's binary_logloss: 0.110186	valid_1's binary_logloss: 0.134716
[100]	training's binary_logloss: 0.110065	valid_1's binary_logloss: 0.134704
[101]	training's binary_logloss: 0.109893	valid_1's binary_logloss: 0.134699
[102]	training's binary_logloss: 0.109786	valid_1's binary_logloss: 0.134724
[103]	training's binary_logloss: 0.109662	valid_1's binary_logloss: 0.134733
[104]	training's binary_logloss: 0.109563	valid_1's binary_logloss: 0.134745
[105]	training's binary_logloss: 0.109446	valid_1's binary_logloss: 0.13472
[106]	training's binary_logloss: 0.109314	valid_1's binary_logloss: 0.13473
[107]	training's binary_logloss: 0.109184	valid_1's binary_logloss: 0.134746
[108]	training's binary_logloss: 0.109062	valid_1's binary_logloss: 0.134767
[109]	training's binary_logloss: 0.10891	valid_1's binary_logloss: 0.134751
[110]	training's binary_logloss: 0.108782	valid_1's binary_logloss: 0.134785
[111]	training's binary_logloss: 0.108679	valid_1's binary_logloss: 0.134794
[112]	training's binary_logloss: 0.108576	valid_1's binary_logloss: 0.134794
[113]	training's binary_logloss: 0.108471	valid_1's binary_logloss: 0.134782
[114]	training's binary_logloss: 0.108374	valid_1's binary_logloss: 0.13478
[115]	training's binary_logloss: 0.108249	valid_1's binary_logloss: 0.13479
[116]	training's binary_logloss: 0.108098	valid_1's binary_logloss: 0.134811
[117]	training's binary_logloss: 0.107962	valid_1's binary_logloss: 0.1348
[118]	training's binary_logloss: 0.107858	valid_1's binary_logloss: 0.134818
[119]	training's binary_logloss: 0.107761	valid_1's binary_logloss: 0.134835
[120]	training's binary_logloss: 0.107683	valid_1's binary_logloss: 0.134841
[121]	training's binary_logloss: 0.107581	valid_1's binary_logloss: 0.134843
[122]	training's binary_logloss: 0.107426	valid_1's binary_logloss: 0.134887
[123]	training's binary_logloss: 0.107341	valid_1's binary_logloss: 0.134894
[124]	training's binary_logloss: 0.107256	valid_1's binary_logloss: 0.134916
[125]	training's binary_logloss: 0.107146	valid_1's binary_logloss: 0.134918
[126]	training's binary_logloss: 0.107053	valid_1's binary_logloss: 0.134923
[127]	training's binary_logloss: 0.106938	valid_1's binary_logloss: 0.134935
[128]	training's binary_logloss: 0.106844	valid_1's binary_logloss: 0.134946
[129]	training's binary_logloss: 0.106755	valid_1's binary_logloss: 0.13497
[130]	training's binary_logloss: 0.106578	valid_1's binary_logloss: 0.134992
[131]	training's binary_logloss: 0.106473	valid_1's binary_logloss: 0.134981
[132]	training's binary_logloss: 0.106391	valid_1's binary_logloss: 0.134966
[133]	training's binary_logloss: 0.106274	valid_1's binary_logloss: 0.134976
[134]	training's binary_logloss: 0.106194	valid_1's binary_logloss: 0.134978
[135]	training's binary_logloss: 0.106027	valid_1's binary_logloss: 0.135
[136]	training's binary_logloss: 0.105839	valid_1's binary_logloss: 0.135053
[137]	training's binary_logloss: 0.105669	valid_1's binary_logloss: 0.135072
[138]	training's binary_logloss: 0.105586	valid_1's binary_logloss: 0.135078
[139]	training's binary_logloss: 0.105509	valid_1's binary_logloss: 0.135085
[140]	training's binary_logloss: 0.105391	valid_1's binary_logloss: 0.135081
[141]	training's binary_logloss: 0.105278	valid_1's binary_logloss: 0.135107
[142]	training's binary_logloss: 0.105139	valid_1's binary_logloss: 0.135096
[143]	training's binary_logloss: 0.105048	valid_1's binary_logloss: 0.135094
[144]	training's binary_logloss: 0.104961	valid_1's binary_logloss: 0.135092
[145]	training's binary_logloss: 0.104888	valid_1's binary_logloss: 0.1351
[146]	training's binary_logloss: 0.104764	valid_1's binary_logloss: 0.135073
[147]	training's binary_logloss: 0.104699	valid_1's binary_logloss: 0.135078
[148]	training's binary_logloss: 0.104605	valid_1's binary_logloss: 0.135105
[149]	training's binary_logloss: 0.104516	valid_1's binary_logloss: 0.135095
[150]	training's binary_logloss: 0.104435	valid_1's binary_logloss: 0.135105
[151]	training's binary_logloss: 0.104357	valid_1's binary_logloss: 0.135102
[152]	training's binary_logloss: 0.104291	valid_1's binary_logloss: 0.135103
[153]	training's binary_logloss: 0.10419	valid_1's binary_logloss: 0.135085
[154]	training's binary_logloss: 0.104093	valid_1's binary_logloss: 0.135096
[155]	training's binary_logloss: 0.104028	valid_1's binary_logloss: 0.135088
[156]	training's binary_logloss: 0.103942	valid_1's binary_logloss: 0.13508
[157]	training's binary_logloss: 0.10383	valid_1's binary_logloss: 0.135074
[158]	training's binary_logloss: 0.103769	valid_1's binary_logloss: 0.135077
[159]	training's binary_logloss: 0.103688	valid_1's binary_logloss: 0.135088
[160]	training's binary_logloss: 0.103588	valid_1's binary_logloss: 0.135114
[161]	training's binary_logloss: 0.103526	valid_1's binary_logloss: 0.135108
[162]	training's binary_logloss: 0.103431	valid_1's binary_logloss: 0.135096
[163]	training's binary_logloss: 0.103327	valid_1's binary_logloss: 0.135082
[164]	training's binary_logloss: 0.103227	valid_1's binary_logloss: 0.135115
[165]	training's binary_logloss: 0.103105	valid_1's binary_logloss: 0.135119
[166]	training's binary_logloss: 0.103043	valid_1's binary_logloss: 0.135116
[167]	training's binary_logloss: 0.102938	valid_1's binary_logloss: 0.135118
[168]	training's binary_logloss: 0.102872	valid_1's binary_logloss: 0.135138
[169]	training's binary_logloss: 0.102772	valid_1's binary_logloss: 0.13514
[170]	training's binary_logloss: 0.102685	valid_1's binary_logloss: 0.135111
[171]	training's binary_logloss: 0.102623	valid_1's binary_logloss: 0.135106
[172]	training's binary_logloss: 0.102496	valid_1's binary_logloss: 0.135125
[173]	training's binary_logloss: 0.102447	valid_1's binary_logloss: 0.135123
[174]	training's binary_logloss: 0.102381	valid_1's binary_logloss: 0.135155
[175]	training's binary_logloss: 0.102315	valid_1's binary_logloss: 0.135159
[176]	training's binary_logloss: 0.10224	valid_1's binary_logloss: 0.135172
[177]	training's binary_logloss: 0.102108	valid_1's binary_logloss: 0.135189
[178]	training's binary_logloss: 0.102013	valid_1's binary_logloss: 0.135207
[179]	training's binary_logloss: 0.101894	valid_1's binary_logloss: 0.135208
[180]	training's binary_logloss: 0.101844	valid_1's binary_logloss: 0.135237
[181]	training's binary_logloss: 0.101723	valid_1's binary_logloss: 0.135266
[182]	training's binary_logloss: 0.101605	valid_1's binary_logloss: 0.135243
[183]	training's binary_logloss: 0.101498	valid_1's binary_logloss: 0.13527
[184]	training's binary_logloss: 0.101361	valid_1's binary_logloss: 0.135281
[185]	training's binary_logloss: 0.101277	valid_1's binary_logloss: 0.135242
[186]	training's binary_logloss: 0.101152	valid_1's binary_logloss: 0.135251
[187]	training's binary_logloss: 0.101091	valid_1's binary_logloss: 0.135248
[188]	training's binary_logloss: 0.100915	valid_1's binary_logloss: 0.135257
[189]	training's binary_logloss: 0.100844	valid_1's binary_logloss: 0.135277
[190]	training's binary_logloss: 0.100746	valid_1's binary_logloss: 0.135292
[191]	training's binary_logloss: 0.100654	valid_1's binary_logloss: 0.135319
[192]	training's binary_logloss: 0.100523	valid_1's binary_logloss: 0.135339
[193]	training's binary_logloss: 0.100429	valid_1's binary_logloss: 0.135342
[194]	training's binary_logloss: 0.100384	valid_1's binary_logloss: 0.135366
[195]	training's binary_logloss: 0.100254	valid_1's binary_logloss: 0.135359
[196]	training's binary_logloss: 0.100124	valid_1's binary_logloss: 0.135382
[197]	training's binary_logloss: 0.100069	valid_1's binary_logloss: 0.135378

LGBMClassifier(learning_rate=0.05, n_estimators=500, random_state=156)

In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score
def get_clf_eval(y_test, pred=None, pred_probs=None):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    roc_auc = roc_auc_score(y_test, pred_probs)  # 수정된 부분

    print(confusion)
    print('*' * 20)
    print(f"Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-Score: {f1}, ROC-AUC: {roc_auc}")
    return roc_auc  # AUC 값을 반환하도록 수정

In [66]:
preds = lgbm_clf.predict(X_test)
pred_proba = lgbm_clf.predict_proba(X_test)[:, 1]

# 성능 평가
lgbm_roc_auc = get_clf_eval(y_test, preds, pred_proba)

[[14565     5]
 [  630     4]]
********************
Accuracy: 0.9582346750855039, Precision: 0.4444444444444444, Recall: 0.006309148264984227, F1-Score: 0.012441679626749611, ROC-AUC: 0.8403631765717119

# XGBM vs LGBM

1. auc 기준 평가 결과
2. 각각의 파라미터 값

In [67]:
# AUC 결과 출력
print(f"XGBoost ROC-AUC: {xgb_roc_score:.4f}")

XGBoost ROC-AUC: 0.8443

In [71]:
print(f"LGBM ROC-AUC : {lgbm_roc_auc:.4f}")

LGBM ROC-AUC : 0.8404

In [69]:
# 모델 파라미터 출력
xgb_params = xgb_clf.get_params()
xgb_params

{'objective': 'binary:logistic',
 'use_label_encoder': True,
 'base_score': 0.5,
 'booster': 'gbtree',
 'colsample_bylevel': 1,
 'colsample_bynode': 1,
 'colsample_bytree': 1,
 'enable_categorical': False,
 'gamma': 0,
 'gpu_id': -1,
 'importance_type': None,
 'interaction_constraints': '',
 'learning_rate': 0.300000012,
 'max_delta_step': 0,
 'max_depth': 6,
 'min_child_weight': 1,
 'missing': nan,
 'monotone_constraints': '()',
 'n_estimators': 100,
 'n_jobs': 20,
 'num_parallel_tree': 1,
 'predictor': 'auto',
 'random_state': 156,
 'reg_alpha': 0,
 'reg_lambda': 1,
 'scale_pos_weight': 1,
 'subsample': 1,
 'tree_method': 'exact',
 'validate_parameters': 1,
 'verbosity': None,
 'n_estimator': 500,
 'learing_rate': 0.05}

In [70]:
# 모델 파라미터 출력
lgbm_params = lgbm_clf.get_params()
lgbm_params

{'boosting_type': 'gbdt',
 'class_weight': None,
 'colsample_bytree': 1.0,
 'importance_type': 'split',
 'learning_rate': 0.05,
 'max_depth': -1,
 'min_child_samples': 20,
 'min_child_weight': 0.001,
 'min_split_gain': 0.0,
 'n_estimators': 500,
 'n_jobs': -1,
 'num_leaves': 31,
 'objective': None,
 'random_state': 156,
 'reg_alpha': 0.0,
 'reg_lambda': 0.0,
 'silent': 'warn',
 'subsample': 1.0,
 'subsample_for_bin': 200000,
 'subsample_freq': 0}